version: 1

formatters:
  simple:
    format: "[%(asctime)s] - %(levelname)s - %(filename)s:%(funcName)s:%(lineno)d - %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
  file_handler_config:
    class: logging.FileHandler
    filename: ./selenium_learning.log
    mode: 'w'
  file_handler:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: simple
    filename: ./selenium_learning.log
    maxBytes: 5242880
    backupCount: 1
    encoding: utf8

root:  # default setting
  level: INFO
  handlers: [file_handler]
