STR_XPATH_BTN_BASIC_MENU = '//*[@id="basic_example"]/span/i'

# Demo element name format: Type_indicate-category_element-type_demo-name_demo-id_demo-element
# Simple Form Demo
STR_XPATH_BTN_SIMPLE_FORM = '//*[@id="basic"]/div/a[1]'
STR_XPATH_INPUT_SIMPLE_SINGLE_MSG = '//*[@id="user-message"]'
STR_XPATH_BTN_SIMPLE_SINGLE_SHOW_MSG = '//*[@id="get-input"]/button'
STR_XPATH_TEXT_SINGLE_SIMPLE_SHOW_TEXT = '//*[@id="display"]'
STR_XPATH_INPUT_SIMPLE_TWO_VAL_A = '//*[@id="sum1"]'
STR_XPATH_INPUT_SIMPLE_TWO_VAL_B = '//*[@id="sum2"]'
STR_XPATH_BTN_SIMPLE_TWO_TOTAL = '//*[@id="gettotal"]/button'
STR_XPATH_TEXT_SIMPLE_TWO_SHOW_SUM = '//*[@id="displayvalue"]'
# Check Box Demo
STR_XPATH_BTN_CHECK_BOX = '//*[@id="basic"]/div/a[2]'
STR_XPATH_CHECKBOX_CHECK_SINGLE_CHECKBOX = '//*[@id="isAgeSelected"]'
STR_XPATH_TEXT_CHECK_SINGLE_SHOW_MSG = '//*[@id="txtAge"]'
STR_XPATH_CHECKBOX_CHECK_MULTIPLE_OPTION_1 = '//*[@id="easycont"]/div/div[2]/div[2]/div[2]/div[1]/label/input'
STR_XPATH_CHECKBOX_CHECK_MULTIPLE_OPTION_2 = '//*[@id="easycont"]/div/div[2]/div[2]/div[2]/div[2]/label/input'
STR_XPATH_CHECKBOX_CHECK_MULTIPLE_OPTION_3 = '//*[@id="easycont"]/div/div[2]/div[2]/div[2]/div[3]/label/input'
STR_XPATH_CHECKBOX_CHECK_MULTIPLE_OPTION_4 = '//*[@id="easycont"]/div/div[2]/div[2]/div[2]/div[4]/label/input'
STR_XPATH_BTN_CHECK_MULTIPLE_ALL = '//*[@id="check1"]'
# Radio Buttons Demo
STR_XPATH_BTN_RADIO_BUTTONS = '//*[@id="basic"]/div/a[3]'
STR_XPATH_RADIO_RADIO_FIRST_RADIO_MALE = '//*[@id="easycont"]/div/div[2]/div[1]/div[2]/label[1]/input'
STR_XPATH_RADIO_RADIO_FIRST_RADIO_FEMALE = '//*[@id="easycont"]/div/div[2]/div[1]/div[2]/label[2]/input'
STR_XPATH_BTN_RADIO_FIRST_SHOW = '//*[@id="buttoncheck"]'
STR_XPATH_TEXT_RADIO_FIRST_SHOW_MSG = '//*[@id="easycont"]/div/div[2]/div[1]/div[2]/p[3]'
STR_XPATH_RADIO_RADIO_GROUP_RADIO_MALE = '//*[@id="easycont"]/div/div[2]/div[2]/div[2]/div[1]/label[1]/input'
STR_XPATH_RADIO_RADIO_GROUP_RADIO_FEMALE = '//*[@id="easycont"]/div/div[2]/div[2]/div[2]/div[1]/label[2]/input'
STR_XPATH_RADIO_RADIO_GROUP_RADIO_0 = '//*[@id="easycont"]/div/div[2]/div[2]/div[2]/div[2]/label[1]/input'
STR_XPATH_RADIO_RADIO_GROUP_RADIO_5 = '//*[@id="easycont"]/div/div[2]/div[2]/div[2]/div[2]/label[2]/input'
STR_XPATH_RADIO_RADIO_GROUP_RADIO_15 = '//*[@id="easycont"]/div/div[2]/div[2]/div[2]/div[2]/label[3]/input'
STR_XPATH_BTN_RADIO_GROUP_SHOW = '//*[@id="easycont"]/div/div[2]/div[2]/div[2]/button'
STR_XPATH_TEXT_RADIO_GROUP_SHOW_MSG = '//*[@id="easycont"]/div/div[2]/div[2]/div[2]/p[2]'
